library(dplyr)
source("format_data.R")
source_data <- format_data()
print("Grouping Data...")
by_subject <- group_by(source_data, Activity, Subject)
print("Data Grouped")
print("Summarizing Data...")
data_summary <- summarize_each(by_subject, funs(mean))
column_names <- colnames(data_summary)
print("Data Summarized -- Saving File...")
write.csv(data_summary, file="tidydata.csv")
write.csv(column_names, file="proto-codebook.csv")
print("File Saved -- Analysis Complete")
